### ISSUE TITLE
Project questions

### ISSUE THREAD

**Issue by Cloolalang** [tinytronix/LoRa#1]
Hi TinyTronix, 
Im interested in your project, I have been working on the Mysensors with RFM95/6 Lora (SX1276) and really want to move on into SX126X for the improved phy and link budgets.
I will build some hardware to test your project, my question is have you tried out the gateway-node over ranges around 5-10km?
Thanks for your good work!
P

**Comment by tinytronix** [comment]
No I didnt check with long distances because the distance heavily depends on antenna setup - and I only have cheap ebay antennas at hand.
