### ISSUE TITLE
Is a SX1262 for Raspberry Pi supported

### ISSUE THREAD

**Issue by Fux2** [tinytronix/LoRa#3]
Hi,
do you know, if this lib is also working on a Raspberry Pi with a SX1262?
I want to use this board
https://de.aliexpress.com/item/4001081597962.html?spm=a2g0o.cart.0.0.47633c00vIzk55&mp=1
for peer 2 peer communication.

As sensor nodes I want to use attnode (www.attno.de).
Can all usual LORA sensors (like attnode) be received by your library (when equal frequency of course)?

Thanks

PS: Impressing work!

**Comment by tinytronix** [comment]
Your preferred board uses UART communication. My library uses the SPI interface of the SX126x chip.
You cannot use my lib with your board.
Also you cannot use the sensors. They are LoraWAN, not peer 2 peer!
Lora is the wireless communication protocol. LoraWAN is a infrastructure on top of it.
