### ISSUE TITLE
Is there future plan to at least make gateway code compatible  for ESP32 ?

### ISSUE THREAD

**Issue by happytm** [tinytronix/LoRa#5]
This is very light weight and simple solution for home automation.

It would be nice to have Gateway on ESP32 hardware so whole network can be controlled from web interface.

I also wanted to ask if  EByte module https://www.ebyte.com/en/product-view-news.aspx?id=437 is supported ?

Thanks.

**Comment by tinytronix** [comment]
I was thinking about designing a module based upon ESP32, but currently I cannot find any time doing this, so: not planned! But if anybody likes to do so, please feel free :)

 The EByte module should be compatible as it uses SX126x chip connected via SPI interface
